# -*- coding: utf-8 -*-
"""Preprocessor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_56sHLEQP0NUDKFo_D4C3tHCapm6DLn
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
from tqdm import tqdm
from scipy.io import loadmat,savemat

!mkdir NTIRE_Validation_Spectral_256

folder_path = '/content/drive/MyDrive/HSFMRGB/Preprocessed_Datasets/NTIRE_Validation_Spectral_256'

path = '/content/drive/MyDrive/HSFMRGB/Original_Datasets/NTIRE2020_Validation_Spectral'
paths = os.listdir(path)
len(paths)

def save(paths,saveto):
  for _path in tqdm(paths):
    p = os.path.join(path,_path)
    img = cv2.imread(p)
    img = cv2.resize(img, (256, 256),interpolation = cv2.INTER_NEAREST)
    cv2.imwrite(os.path.join(folder_path,_path),img)
save(paths,saveto=folder_path)

def save_spec(paths,saveto):
  for _path in tqdm(paths):
    p = os.path.join(path,_path)
    data = loadmat(p)
    img,bands = data['cube'],data['bands']
    img = cv2.resize(img, (256, 256),interpolation = cv2.INTER_NEAREST)
    savemat(os.path.join(folder_path,_path),mdict={'bands':bands,'cube':img})
save_spec(paths,saveto=folder_path)

print(len(os.listdir(folder_path)))
print(len(os.listdir(path)))
# print(len(os.listdir('/content/drive/MyDrive/HSFMRGB/Preprocessed_Datasets/NTIRE_Train_Spectral_256')))